import DropdownSection from "../../components/DropdownSection/DropdownSection";
import AvailableRoom from "../../components/AvailableRoom/AvailableRoom";
import "./Rooms.scss";

const Rooms = () => {
  return (
    <main className="rooms">
      <DropdownSection />
      <AvailableRoom
        name="Natures Nest"
        description="Welcome to Nature's Nest, the eco-friendly hotel room that invites you
        to enjoy a sustainable and nature-inspired experience. Our room design
        incorporates natural materials, such as wooden furniture and recycled
        textiles, which create a warm and cozy atmosphere. All of the
        electricity used in the room is generated by solar panels, reducing our
        carbon footprint."
        price={299}
        toilets={1}
        beds={1}
      />
      <AvailableRoom
        name="Organic Comfort"
        description="An eco-friendly hotel room with 2 king-size beds and 2 toilets provides guests with comfortable and sustainable accommodation. The room is designed with a focus on reducing the environmental impact of traditional hotels while ensuring that guests have access to modern amenities."
        price={399}
        toilets={2}
        beds={2}
      />
      <AvailableRoom
        name="Green Getaway"
        description="An eco-friendly hotel room with 3 king-size beds and 3 toilets is a perfect choice for families or groups of friends who are looking for sustainable and comfortable accommodation. The room is designed to provide guests with modern amenities while minimizing its environmental impact."
        price={499}
        toilets={3}
        beds={3}
      />
    </main>
  );
};

export default Rooms;
